version: '3.9'
services:
  backend: 
    build: .
    ports:
     - 8000:3000
    volumes:
     - .:/app
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379
     
    
